trigger:
  branches:
    include:
      - main
  paths:
    include:
      - api/**
      - azure-pipelines.yml

pool:
  vmImage: ubuntu-latest

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2

steps:
  - task: Cache@2
    inputs:
      key: 'maven | "$(Agent.OS)" | api/pom.xml'
      restoreKeys: 'maven | "$(Agent.OS)"'
      path: $(MAVEN_CACHE_FOLDER)


  - task: Maven@4
    displayName: 'Build & test (Java 17)'
    inputs:
      mavenPomFile: 'api/pom.xml'
      goals: 'clean verify'
      options: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
      jdkVersionOption: '1.17'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'api/target'
      ArtifactName: 'api-target'
